-- MySQL Script generated by MySQL Workbench
-- 01/08/17 00:15:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`SUBJECT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SUBJECT` (
  `SUBJECT_ID` INT NOT NULL,
  `NAME` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`SUBJECT_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SUBJECT_FORM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SUBJECT_FORM` (
  `SUBJECT_FORM_ID` INT NOT NULL,
  `NAME` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`SUBJECT_FORM_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GROUP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GROUP` (
  `GROUP_ID` INT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`GROUP_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USER` (
  `USER_ID` INT NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `PASSWORD` VARCHAR(60) NOT NULL,
  `ROLE` VARCHAR(50) NOT NULL,
  `FIRST_NAME` VARCHAR(50) NOT NULL,
  `LAST_NAME` VARCHAR(50) NOT NULL,
  `PESEL` DECIMAL(11,0) NOT NULL,
  PRIMARY KEY (`USER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`WORKER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`WORKER` (
  `WORKER_ID` INT NOT NULL,
  `USER_ID` INT NOT NULL,
  PRIMARY KEY (`WORKER_ID`, `USER_ID`),
  INDEX `fk_WORKER_USER1_idx` (`USER_ID` ASC),
  CONSTRAINT `fk_WORKER_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `mydb`.`USER` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SUBJECT_BLOCK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SUBJECT_BLOCK` (
  `SUBJECT_BLOCK_ID` INT NOT NULL,
  `SUBJECT_ID` INT NOT NULL,
  `SUBJECT_FORM_ID` INT NOT NULL,
  `GROUP_ID` INT NOT NULL,
  `WORKER_ID` INT NOT NULL,
  PRIMARY KEY (`SUBJECT_BLOCK_ID`, `SUBJECT_ID`, `SUBJECT_FORM_ID`, `GROUP_ID`, `WORKER_ID`),
  INDEX `fk_STUDENT_SUBJECT_SUBJECT1_idx` (`SUBJECT_ID` ASC),
  INDEX `fk_STUDENT_SUBJECT_SUBJECT_FORM1_idx` (`SUBJECT_FORM_ID` ASC),
  INDEX `fk_STUDENT_SUBJECT_GROUP1_idx` (`GROUP_ID` ASC),
  INDEX `fk_SUBJECT_BLOCK_WORKER1_idx` (`WORKER_ID` ASC),
  CONSTRAINT `fk_STUDENT_SUBJECT_SUBJECT1`
    FOREIGN KEY (`SUBJECT_ID`)
    REFERENCES `mydb`.`SUBJECT` (`SUBJECT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STUDENT_SUBJECT_SUBJECT_FORM1`
    FOREIGN KEY (`SUBJECT_FORM_ID`)
    REFERENCES `mydb`.`SUBJECT_FORM` (`SUBJECT_FORM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STUDENT_SUBJECT_GROUP1`
    FOREIGN KEY (`GROUP_ID`)
    REFERENCES `mydb`.`GROUP` (`GROUP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SUBJECT_BLOCK_WORKER1`
    FOREIGN KEY (`WORKER_ID`)
    REFERENCES `mydb`.`WORKER` (`WORKER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`STUDENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`STUDENT` (
  `INDEX_NO` DECIMAL(10,0) NOT NULL,
  `USER_ID` INT NOT NULL,
  PRIMARY KEY (`INDEX_NO`, `USER_ID`),
  INDEX `fk_STUDENT_USER1_idx` (`USER_ID` ASC),
  CONSTRAINT `fk_STUDENT_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `mydb`.`USER` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`STUDENT_SUBJECT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`STUDENT_SUBJECT` (
  `STUDENT_SUBJECT_ID` INT NOT NULL,
  `SUBJECT_BLOCK_ID` INT NOT NULL,
  `INDEX_NO` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`STUDENT_SUBJECT_ID`, `SUBJECT_BLOCK_ID`, `INDEX_NO`),
  INDEX `fk_STUDENT_SUBJECT_SUBJECT_BLOCK1_idx` (`SUBJECT_BLOCK_ID` ASC),
  INDEX `fk_STUDENT_SUBJECT_STUDENT1_idx` (`INDEX_NO` ASC),
  CONSTRAINT `fk_STUDENT_SUBJECT_SUBJECT_BLOCK1`
    FOREIGN KEY (`SUBJECT_BLOCK_ID`)
    REFERENCES `mydb`.`SUBJECT_BLOCK` (`SUBJECT_BLOCK_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STUDENT_SUBJECT_STUDENT1`
    FOREIGN KEY (`INDEX_NO`)
    REFERENCES `mydb`.`STUDENT` (`INDEX_NO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GRADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GRADE` (
  `GRADE_ID` INT NOT NULL,
  `GRADE` INT NOT NULL,
  `DATE` DATETIME NOT NULL,
  `DESCRIPTION` VARCHAR(255) NOT NULL,
  `STUDENT_SUBJECT_ID` INT NOT NULL,
  PRIMARY KEY (`GRADE_ID`, `STUDENT_SUBJECT_ID`),
  INDEX `fk_GRADE_STUDENT_SUBJECT1_idx` (`STUDENT_SUBJECT_ID` ASC),
  CONSTRAINT `fk_GRADE_STUDENT_SUBJECT1`
    FOREIGN KEY (`STUDENT_SUBJECT_ID`)
    REFERENCES `mydb`.`STUDENT_SUBJECT` (`STUDENT_SUBJECT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
